export enum ErrorType {
    OBJECT_NOT_FOUND_ERROR = "OBJECT_NOT_FOUND_ERROR",
    ACCESSING_UNDEFINED_ERROR = "ACCESSING_UNDEFINED_ERROR",
    TYPE_ERROR= "TYPE_ERROR",
    INPUT_ERROR ="INPUT_ERROR"
}